## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost/testdb5
    platform: postgres
    initialization-mode: always
    continue-on-error: false
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /api

jwtSecret: co.com
jwtExpiration: 3600

